### ISSUE TITLE
Feature: Could we get release date of the latest version on command line

### ISSUE THREAD

**Issue by lamyergeier** [dvershinin/lastversion#121]
For example I would like to do on bash (to get the release date of the latest version on command line)

```
lastversion https://github.com/mpv-player/mpv --date
```

**Comment by dvershinin** [comment]
You can do it like this: `lastversion --format json https://github.com/mpv-player/mpv | jq -r .tag_date`

**Comment by lamyergeier** [comment]
Will this method work for every  github and gitlab repository?

**Comment by lamyergeier** [comment]
Didn't work in the following case

```
$ lastversion --format json https://github.com/Second-Hand-Friends/kleinanzeigen-bot  | jq -r .tag_date
CRITICAL: No release was found
```

**Comment by dvershinin** [comment]
@lamyergeier it didn't work because the last release is called "latest" and does not have any clear version number (last version does not support a version that is not defined by some numerics at least), while all the remaining versions there are marked as pre-releases. Maybe you want `--pre` for getting last release and not `latest`:

```lastversion --pre --format json https://github.com/Second-Hand-Friends/kleinanzeigen-bot  | jq -r .tag_date```
