### ISSUE TITLE
Only download last version if you have not already

### ISSUE THREAD

**Issue by 5c0tt-b0t** [dvershinin/lastversion#19]
First... THANK YOU for LastVersion! It is amazing!!
Please close this ASAP as its more a feature request than an issue.
I am trying to keep software updated once per week, but i do not want to download a gigabyte every week to find out half of it is not updated from last week (same version still) is there OR could there be a way too download my list of releases only if it is a new version? (not just last version) Thank you for your work, its appreciated!

**Comment by dvershinin** [comment]
Hi @5c0tt-b0t ,

It depends: 

If you "install" an *RPM* asset from GitHub, using `lastversion install <reponame>` then it should not download something in vain. It will consult the RPM database, will check what is the current version of the thing you installing, and skip downloading if it's not newer on GitHub. This is a bit limited because it makes the assumption that package name equals `<reponame> `. Plus, you *have* to install `lastversion` itself via RPM so it has access to RPM Python modules. So this is quite limited.

E.g. if you do this in CentOS 8:

```
sudo yum -y install https://extras.getpagespeed.com/release-latest.rpm
sudo yum install lastversion
...
sudo lastversion install mailspring
```

Then it will work as intended. It finds Mailspring on Github, finds its `.rpm` assets, checks if "mailspring" package is installed, and see if it's older than on Github, before downloading.

If you're not using RPM-based install of `lastversion` or not downloading `.rpms` with it, then this won't work and you have to script whichever way to compare what version you already have before downloading.

You'll use something like [this](https://github.com/dvershinin/lastversion#check-for-new-release).
Just need to store the "last downloaded version" somewhere, e.g.

```
EXISTING_VER=$(cat version.txt)
LASTVER=$(lastversion repo/owner -gt ${EXISTING_VER})
if [[ $? -eq 0 ]]; then
  # LASTVER is newer
  lastversion download repo/owner
  echo $LASTVER > version.txt 
fi
```

This uses `-gt` switch which compares what's latest to a given version, e.g. `lastversion repo/owner -gt 1.2.3` will return 0 exit code if the version on GitHub is newer than 1.2.3.
