### ISSUE TITLE
Last version isn't actually last verison. It's last published version

### ISSUE THREAD

**Issue by Brightside56** [dvershinin/lastversion#21]
Hello

Few days ago I've seen Prometheus update where they published v2.19.1 and v2.20.0 on Github at same time, but v2.19.1 was shown by Lastversion as latest one. Is this bug or Lastversion doesn't take into consideration multiple releases to aggregate latest one according semver or other standard?

**Comment by dvershinin** [comment]
@Brightside56 It is a sort of intentional behavior because the latest version chronologically is the one that is considered "last".
The reason being is that quite many releasers tend to switch the version scheme completely, so "latest version by semver" may result in a release that is years old, just because it's "higher", and weeding out such cases needs quite some extra handling.

Yet there are some repos, where "latest chronologically" may be not truly the latest. Especially applies to patch releases, or where several version branches are maintained at the same time. 
For Prometheus, it's currently returning `2.20.1`, which I think is correct, but at some point, it was wrong as you said.

I think I'm seeing a similar case with [magento 2](https://github.com/magento/magento2/tags), where they first posted, e.g. `2.4.0`, then patch version, `2.3.5-p2`, so now incorrectly returning this as the last...

I think we can just look one next tag and aggregate across the two? In most cases that should be sufficient so as to both return correct version and not return old release where version scheme was different.

I'll set up a test repo similiar to magento 2 so that it's added to the test suite.

**Comment by dvershinin** [comment]
It should work fine in the latest `lastversion` v1.1.7. It will consider older tags that are newer, as long as they are not _too_ old.
The test case for this was added also.
