### ISSUE TITLE
Lastversion for Bookstack App 

### ISSUE THREAD

**Issue by atroubat** [dvershinin/lastversion#56]
Hello,

I have an issue with the latest available version of Bookstack App, they named their versions like this: 21.05.1, 21.05.2, etc 
(link to their repo : https://github.com/BookStackApp/BookStack/releases/tag/v21.05.3)

When I run the lastversion command, it removes a 0 : 
```
[root@master ~]# lastversion bookstack
21.5.3
```

Is there a way to fix this and get the right version returned? 
Thanks 

atroubat

**Comment by dvershinin** [comment]
@atroubat it's actually intentional and biased normalization that lastversion does.
Any specific requirement why you need the non-normalized version?

If you need a bare GitHub tag corresponding to release, you can format output as json and pass to `jq`:

```console
[user@linux ~]# lastversion https://github.com/BookStackApp/BookStack --format json | jq -r .tag_name
v21.05.3
```

**Comment by atroubat** [comment]
I do a comparison with the current installed version on my server and as it isn't exactly matching it raises an error in my supervision system 

Ok perfect that's all I need, thanks for your help ! 
I'm closing the issue 

Thank you for your amazing work, have a good day ! 
atroubat

**Comment by dvershinin** [comment]
@atroubat  I probably mislead you a little, from a better solution. For you use case, you can use the scripting helper of `lastversion` available via `-gt` switch. Even if your currently installed version has a non-canonical version format (e.g. with leading zeroes), this can work fine:

```bash
CURRENTLY_INSTALLED="21.05.4"
LASTVER=$(lastversion  https://github.com/BookStackApp/BookStack -gt ${CURRENTLY_INSTALLED})
if [[ $? -eq 0 ]]; then
  # LASTVER is newer, do whatever you want to do on new version being available
  # ....
fi
```

Why this works is because it will normalize (strip leading zeroes) for both the latest version and the currently installed version.
You can further get the proper download URL with `lastversion ... --format source` if needed.
