### ISSUE TITLE
no assets found when ci/cd is working?

### ISSUE THREAD

**Issue by pierrehenrymuller** [dvershinin/lastversion#60]
Hi,

I have discovered your amazing tool, and I have tested in a Fedora the install feature (it will be great to support apt too if deb is finded).

I have tested the Drawio desktop client who provides binaries and packages in the release https://github.com/jgraph/drawio-desktop/releases
But a new version was published 2 hours ago, the 15.3.7 but was not declared as "Latest release". I suppose that CI/CD is building binaries and the flag "Latest release" will move when all is done.

It's possible to point on "Latest release" and not only to the latest version?

The consequence is that I have : ERROR: No assets found to install
for `lastversion install -y jgraph/drawio-desktop`

There is a screenshot and the source code of the releases page : 

![Capture d’écran du 2021-09-28 17-51-10](https://user-images.githubusercontent.com/16239815/135122964-e4cf7f2b-9562-47f2-b15e-9b3f13adf8e2.png)
[https _github.com_jgraph_drawio-desktop_releases.txt](https://github.com/dvershinin/lastversion/files/7245756/https._github.com_jgraph_drawio-desktop_releases.txt)

**Comment by dvershinin** [comment]
Hi,

At the time of the writing (the screenshot), the 15.3.7 is indeed the latest stable version.
There was a formal release which you saw on the GitHub release page (15.2.7), but in most cases, when you see such a situation, it is due to an error/delay from the maintainers of a repository, they either did not have the time to file the 15.3.7 as formal release using GitHub UI or didn't run through CI/CD to generate assets, etc.

Now, I see as predicted, 15.3.7 is both the latest stable and formal release.

If you only want the "latest release" as the latest (and not actually latest), you may want to use `--having-asset` flag. If you ran it during the screenshot time", you would get the desired result. 

Examples:

```
# only return latest release which is formal/has assets other than source code
lastversion 'jgraph/drawio-desktop' --having-asset # > 15.3.7
# only return latest release which has .rpm assets
lastversion jgraph/drawio-desktop --having-asset "~\.rpm$" # > 15.1.3
```

Now, when you run "install" command it will fail unless you specify `--having-asset` like in the last invocation example.. *Maybe* it should default to `--having-asset "~\.rpm$"` when `install` is used. I'm not sure which is most desirable assumption by default: "install truly latest release's RPM or fail if it doesn't have one" or "install the latest release which has RPM".

**Comment by pierrehenrymuller** [comment]
It's clear thanks.

I hope that install is to download the latest rpm available and if you make this for deb too, it's more logical.

I have integrated this command in an ansible playbook for post install a Fedora desktop, so the goal is to have the latest version of package available. If I add ignore_error: true the fail do not block the playbook but the workstation doesn't not have the software installed.

So I vote for the second choice, install the latest release which has rpm when install is set.

**Comment by pierrehenrymuller** [comment]
Thanks

**Comment by dvershinin** [comment]
Changed the default in v2.0.0 to install only releases with .rpm assets.
