### ISSUE TITLE
404 on download url redis

### ISSUE THREAD

**Issue by eilandert** [dvershinin/lastversion#66]
Hi,

When I try to fetch the downloadurl of redis I get a 404 on the returned URL. Any idea what's going on?

eilander@build:/tmp$ lastversion redis --source
https://github.com/redis/redis/archive/6.2.6/redis-6.2.6.tar.gz

eilander@build:/tmp$ lastversion --version
lastversion 2.0.1, up to date

**Comment by dvershinin** [comment]
Hi @eilandert ,

Unfortunately, GitHub suddenly stopped supporting this URL format for downloads: 

`https://github.com/OWNER/PROJECT/archive/%{gittag}/%{name}-%{version}.tar.gz`.

Which, I believe, is a bug. Because such URL format is widely used, e.g. [by Fedora](https://docs.fedoraproject.org/en-US/packaging-guidelines/SourceURL/) for referencing GitHub releases.

So I am hoping this will be fixed _soon_.

In the meanwhile, I could have used a different URL format that does work, but this will result in 6.2.6.tar.gz file as opposed to redis-6.2.6.tar.gz which might break a lot of things furthermore for many people, as the resulting filenames are different...

I have reported this in the GitHub bug reporting [here](https://support.github.com/contact/bug-report?tags=dotcom-contact) with this complaint:

> Since around 2 days ago, links of this format no longer work:

> https://github.com/OWNER/PROJECT/archive/%{gittag}/%{name}-%{version}.tar.gz 

> Such format is used widely by Fedora packages. Many builds are now breaking as they return 404 on downloading release archives...

For anyone affected I suggest doing the same to expedite the resolution.

**Comment by dvershinin** [comment]
@eilandert apparently the issue has now been addressed by GitHub, and the mentioned URL format now works again.

**Comment by eilandert** [comment]
Thanks for the solution, your work and your support. Lastversion is a great tool.
